const CocktailList = [
  {
    id: 1,
    title: "Cocktail gin",
    category: "cocktail gin",
    price: 15.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC3oIdCT8YCOA-vPF5wDb4QYa4ySq076PpXw&usqp=CAU",
    desc: `cold-pressed `,
  },
  {
    id: 2,
    title: "Vodka",
    category: "vodka",
    price: 13.99,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Smirnoff_Red_Label_8213.jpg/1200px-Smirnoff_Red_Label_8213.jpg",
    desc: `vaporware iPhone  `,
  },
  {
    id: 3,
    title: "vodka 1.0",
    category: "cocktail gin",
    price: 6.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC3oIdCT8YCOA-vPF5wDb4QYa4ySq076PpXw&usqp=CAU",
    desc: `ombucha chillwave `,
  },
  {
    id: 4,
    title: "country delight",
    category: "vodka",
    price: 20.99,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Smirnoff_Red_Label_8213.jpg/1200px-Smirnoff_Red_Label_8213.jpg",
    desc: `Shabby chic `,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC3oIdCT8YCOA-vPF5wDb4QYa4ySq076PpXw&usqp=CAU",
    desc: `franzen vegan  `,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "cocktail gin",
    price: 18.99,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Smirnoff_Red_Label_8213.jpg/1200px-Smirnoff_Red_Label_8213.jpg",
    desc: `Portland`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "vodka",
    price: 8.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC3oIdCT8YCOA-vPF5wDb4QYa4ySq076PpXw&usqp=CAU",
    desc: `carry jianbing  `,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC3oIdCT8YCOA-vPF5wDb4QYa4ySq076PpXw&usqp=CAU",
    desc: `on it `,
  },
  {
    id: 9,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Smirnoff_Red_Label_8213.jpg/1200px-Smirnoff_Red_Label_8213.jpg",
    desc: `lorem  `,
  },
];

export default CocktailList;
